SET(GRAPHCUT_INCLUDE_DIR ${EXTERN_PROJECT_SRC_DIR}/graphcut/include)

FIND_LIBRARY(GRAPHCUT_LIBRARIES libgc1.a
  ${GLOBAL_BUILD_DIR}/extern/graphcut/
  ${GLOBAL_BUILD_DIR}/lib/
)

IF (GRAPHCUT_INCLUDE_DIR)
  SET(GRAPHCUT_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found GRAPHCUT include dir yeah baby: ${GRAPHCUT_INCLUDE_DIR}")
ELSE(GRAPHCUT_INCLUDE_DIR)
 MESSAGE(STATUS "/!\ /!\ Not Found : GRAPHCUT include dir : ${GRAPHCUT_INCLUDE_DIR}")
ENDIF (GRAPHCUT_INCLUDE_DIR)

IF (GRAPHCUT_LIBRARIES)
  SET(GRAPHCUT_LIB_FOUND "YES")
  MESSAGE(STATUS "Found GRAPHCUT lib: ${GRAPHCUT_LIBRARIES}")
ELSE(GRAPHCUT_LIBRARIES) 
 MESSAGE(STATUS "/!\ /!\ Not Found : GRAPHCUT libs : ${MAIN_PROJECT_DIR}")
ENDIF (GRAPHCUT_LIBRARIES)


IF(GRAPHCUT_LIB_FOUND AND GRAPHCUT_INCLUDE_FOUND)
  SET(GRAPHCUT_FOUND "YES")
ENDIF(GRAPHCUT_LIB_FOUND AND GRAPHCUT_INCLUDE_FOUND)
