FIND_PATH(TINYPLY_INCLUDE_DIR tinyply.h 
  ${EXTERN_PROJECT_SRC_DIR}/tinyply/source/
)

SET(TINYPLY_INCLUDE_DIR ${EXTERN_PROJECT_SRC_DIR}/tinyply/source)

FIND_LIBRARY(TINYPLY_LIBRARIES libtinyply.a
  ${GLOBAL_BUILD_DIR}/lib/
)

IF (TINYPLY_INCLUDE_DIR)
  SET(TINYPLY_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found TINYPLY include dir: ${TINYPLY_INCLUDE_DIR}")
ELSE(TINYPLY_INCLUDE_DIR)
 MESSAGE(STATUS "/!\ /!\ Not Found : TINYPLY include dir ")
ENDIF (TINYPLY_INCLUDE_DIR)

IF (TINYPLY_LIBRARIES)
  SET(TINYPLY_LIB_FOUND "YES")
  MESSAGE(STATUS "Found TINYPLY lib: ${TINYPLY_LIBRARIES}")
ELSE(TINYPLY_LIBRARIES) 
 MESSAGE(STATUS "/!\\ /!\\ Not Found : TINYPLY libs in : ${EXTERN_PROJECT_SRC_DIR}/tinyply/lib")
ENDIF (TINYPLY_LIBRARIES)


IF(TINYPLY_LIB_FOUND AND TINYPLY_INCLUDE_FOUND)
  SET(TINYPLY_FOUND "YES")
ENDIF(TINYPLY_LIB_FOUND AND TINYPLY_INCLUDE_FOUND)
