FIND_PATH(DDTLIB_INCLUDE_DIR DDT.hpp
  ${DDT_MAIN_DIR}/src/core/

)
FIND_LIBRARY(DDTLIB_LIBRARIES libddt.so
  ${GLOBAL_BUILD_DIR}/   ${GLOBAL_BUILD_DIR}/lib
)


IF (DDTLIB_INCLUDE_DIR)
  SET(DDTLIB_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found DDTLIB include dir: ${DDTLIB_INCLUDE_DIR}")
ELSE(DDTLIB_INCLUDE_DIR)
  MESSAGE(STATUS "[ERROR] DDTLIB include dir not found ==> ${DDTLIB_INCLUDE_DIR}")
ENDIF (DDTLIB_INCLUDE_DIR)

IF (DDTLIB_LIBRARIES)
  SET(DDTLIB_LIB_FOUND "YES")
  MESSAGE(STATUS "Found DDTLIB lib: ${DDTLIB_LIBRARIES}")
ELSE(DDTLIB_LIBRARIES)
  MESSAGE(STATUS "[ERROR] DDTLIB libraries  not found ==> ${DDTLIB_LIBRARIES}")
ENDIF (DDTLIB_LIBRARIES)

IF(DDTLIB_LIB_FOUND AND DDTLIB_INCLUDE_FOUND)
  SET(DDTLIB_FOUND "YES")
ENDIF(DDTLIB_LIB_FOUND AND DDTLIB_INCLUDE_FOUND)
