FIND_PATH(PUGIXML_INCLUDE_DIR pugixml.hpp 
  ${EXTERN_PROJECT_SRC_DIR}/pugixml/include/

)
FIND_LIBRARY(PUGIXML_LIBRARIES libpugixml.a
  ${EXTERN_PROJECT_SRC_DIR}/pugixml/lib/
)


IF (PUGIXML_INCLUDE_DIR)
  SET(PUGIXML_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found PUGIXML include dir: ${PUGIXML_INCLUDE_DIR}")
ENDIF (PUGIXML_INCLUDE_DIR)

IF (PUGIXML_LIBRARIES)
  SET(PUGIXML_LIB_FOUND "YES")
  MESSAGE(STATUS "Found PUGIXML lib: ${PUGIXML_LIBRARIES}")
ENDIF (PUGIXML_LIBRARIES)

IF(PUGIXML_LIB_FOUND AND PUGIXML_INCLUDE_FOUND)
  SET(PUGIXML_FOUND "YES")
ENDIF(PUGIXML_LIB_FOUND AND PUGIXML_INCLUDE_FOUND)
