SET(QPBO_INCLUDE_DIR ${EXTERN_PROJECT_SRC_DIR}/QPBO/include )
FIND_LIBRARY(QPBO_LIBRARIES libqpbo.a
  ${GLOBAL_BUILD_DIR}/extern/QPBO/
  ${GLOBAL_BUILD_DIR}/lib/
)


IF (QPBO_INCLUDE_DIR)
  SET(QPBO_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found QPBO include dir: ${QPBO_INCLUDE_DIR}")
else (QPBO_INCLUDE_DIR)
  MESSAGE(STATUS "!!!! ERROR NOT FOUBD QPBO include dir: ${QPBO_INCLUDE_DIR}")
ENDIF (QPBO_INCLUDE_DIR)

IF (QPBO_LIBRARIES)
  SET(QPBO_LIB_FOUND "YES")
  MESSAGE(STATUS "Found QPBO lib: ${QPBO_LIBRARIES}")
else (QPBO_LIBRARIES)
  MESSAGE(STATUS "ERRPR NOT Found QPBO lib: ${QPBO_LIBRARIES}")
ENDIF (QPBO_LIBRARIES)

IF(QPBO_LIB_FOUND AND QPBO_INCLUDE_FOUND)
  SET(QPBO_FOUND "YES")
ENDIF(QPBO_LIB_FOUND AND QPBO_INCLUDE_FOUND)
